# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'webScrapingWithSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftSoup'
pod 'Erik'

  # Pods for webScrapingWithSwift

end
